version: '3.4'

services:
  reverseproxy:
    image: traefik:v2.9
    labels:
      - "traefik.enable=true"
      - "service.owner=igor"
      - "traefik.http.routers.api.rule=Host(`traefik.igor.moomers.org`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=basicauth@file"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=le"
      - "traefik.http.routers.api.entrypoints=https"
    ports:
      - "173.236.34.123:80:80"
      - "173.236.34.123:443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/igor47/repos/igor.services/config/traefik:/etc/traefik
      - /home/igor47/services/traefik/acme:/acme

  miniflux:
    image: miniflux/miniflux:latest
    labels:
      - "traefik.enable=true"
      - "service.owner=igor"
      - "traefik.http.routers.miniflux.rule=Host(`miniflux.igor.moomers.org`)"
      - "traefik.http.routers.miniflux.tls=true"
      - "traefik.http.routers.miniflux.tls.certresolver=le"
      - "traefik.http.routers.miniflux.entrypoints=https"
    ports:
      - "127.0.0.1::8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://miniflux:R72Zttsgd@postgres/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=igor47
      - ADMIN_PASSWORD=sunshine
      - BASE_URL=https://miniflux.igor.moomers.org/

  postgres:
    image: postgres:latest
    labels:
      - "traefik.enable=false"
      - "service.owner=igor"
    ports:
      - "127.0.0.1::5432"
    environment:
      - POSTGRES_PASSWORD=H6FtGThfirGF9J
    volumes:
      - /home/igor47/services/postgres/data:/var/lib/postgresql/data
      - /home/igor47/repos/igor.services/init_scripts:/init_scripts
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      start_period: 30s

  caddy:
    image: caddy:latest
    labels:
      - "traefik.enable=true"
      - "service.owner=igor"
      - "traefik.http.routers.caddy.rule=Host(`igor.moomers.org`)"
      - "traefik.http.routers.caddy.tls=true"
      - "traefik.http.routers.caddy.tls.certresolver=le"
      - "traefik.http.routers.caddy.entrypoints=https"
      - "traefik.http.routers.igor47.rule=Host(`igor47.com`,`www.igor47.com`)"
    ports:
      - "127.0.0.1::80"
      - "127.0.0.1::443"
    volumes:
      - /home/igor47/repos/igor.services/config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/igor47/www:/www
      - /home/igor47/services/caddy/data:/data
      - /home/igor47/services/caddy/config:/config
