version: '3.4'

services:
  reverseproxy:
    image: traefik:v2.9
    labels:
      - "traefik.enable=true"
      - "service.owner=igor"
    ports:
      # The HTTP port
      - "127.0.0.1:80:80"
      # The Web UI (enabled by api.insecure=true)
      - "127.0.0.1:8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/igor47/repos/igor.services/config/traefik:/etc/traefik

  miniflux:
    image: miniflux/miniflux:latest
    labels:
      - "traefik.enable=true"
      - "service.owner=igor"
    ports:
      - "127.0.0.1:47081:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://miniflux:R72Zttsgd@postgres/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=igor47
      - ADMIN_PASSWORD=sunshine
      - BASE_URL=https://igor.moomers.org/miniflux/

  postgres:
    image: postgres:latest
    labels:
      - "traefik.enable=false"
      - "service.owner=igor"
    ports:
      - "127.0.0.1::5432"
    environment:
      - POSTGRES_PASSWORD=H6FtGThfirGF9J
    volumes:
      - /home/igor47/services/postgres/data:/var/lib/postgresql/data
      - /home/igor47/repos/igor.services/init_scripts:/init_scripts
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      start_period: 30s
