## traefik.yml
#
## Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
    exposedByDefault: false
    constraints: "Label(`service.owner`, `igor`)"

# API and dashboard configuration
api:
  dashboard: true

# http config
http:
  middlewares:
    basicauth: # the name of the auth middleware
      basicAuth:
        users: # example: `htpasswd -nB igor`
          - igor:$2y$05$6Q7NMsvf/K3/7E3CWoiXM.0/Vk0zA1gSsbFUDNADBjLUWblyxz7zK
