## traefik.yml
#
## Docker configuration backend
providers:
  docker:
    exposedByDefault: false
    constraints: "Label(`service.owner`, `igor`)"
  file:
    directory: /etc/traefik
    watch: true

# API and dashboard configuration
api:
  dashboard: true

entrypoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
  syncthingtcpe:
    address: ":22047"
  syncthingudpe:
    address: ":22047/udp"

certificatesResolvers:
  le:
    acme:
      email: igor@moomers.org
      storage: /acme/acme.json
      httpChallenge:
        entrypoint: http
      tlsChallenge: {}
    
# http config
http:
  middlewares:
    basicauth: # the name of the auth middleware
      basicAuth:
        users: # example: `htpasswd -nB igor`
          - igor47:$2y$05$CcGRgq4dq8r0AIHdcYYazuuWSn01O/bg493OcdbaE2Hm45qURTzye
